spring:
  docker:
    compose:
      enabled: false
  r2dbc:
    host: localhost
    port: 5433
    database: postgres
    schema: public
    username: postgres
    password: 123456pragma

server:
  port: 8085

cors:
  allowed-origins:
    - http://localhost:4200
    - http://localhost:3000

