spring:
  docker:
    compose:
      enabled: false
  r2dbc:
    host: localhost
    port: 5434
    database: postgres
    schema: public
    username: postgres
    password: 123456pragma

cors:
  allowed-origins:
    - http://localhost:4200
    - http://localhost:3000

jwt:
  secret: ${JWT_SECRET:mySuperSecureJwtSecretKeyThatIsLongEnough123!}
  expiration: ${JWT_EXPIRATION:3600000}

